import { MigrationInterface, QueryRunner } from "typeorm";

export class BaselineSchema1769191983739 implements MigrationInterface {
    name = 'BaselineSchema1769191983739'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "Permissions" ("Id" int NOT NULL IDENTITY(1,1), "Name" varchar(255) NOT NULL, "Description" varchar(500), "CreatedAt" datetime NOT NULL CONSTRAINT "DF_61e5432cbbd5b90293faa041a4e" DEFAULT getdate(), CONSTRAINT "UQ_f685112ff526e2c420042c1368f" UNIQUE ("Name"), CONSTRAINT "PK_99fa50928aea3ac88937056e3dd" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE TABLE "PermissionsByUser" ("Id" int NOT NULL IDENTITY(1,1), "UserId" int NOT NULL, "PermissionId" int NOT NULL, "AssignedAt" datetime NOT NULL CONSTRAINT "DF_683f38da63ac57f49e315168726" DEFAULT getdate(), CONSTRAINT "UQ_dd300d291e46a5fdc6c634714ce" UNIQUE ("UserId", "PermissionId"), CONSTRAINT "PK_8f8d088aa83746f7a91066bb0c9" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE INDEX "IX_PermissionsByUser_UserId" ON "PermissionsByUser" ("UserId") `);
        await queryRunner.query(`CREATE TABLE "LoadDocumentsOcByUser" ("Id" int NOT NULL IDENTITY(1,1), "IdUser" int NOT NULL, "IdFolder" uniqueidentifier NOT NULL, "Fecha" datetime NOT NULL CONSTRAINT "DF_ada706f300c8f8fbb1b34747d10" DEFAULT getdate(), "Status" varchar(50), "FileName" varchar(255) NOT NULL, CONSTRAINT "PK_1a6eb7a78ac820c6f236e679787" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE TABLE "Notifications" ("Id" int NOT NULL IDENTITY(1,1), "UserId" int NOT NULL, "Title" varchar(255) NOT NULL, "Message" text NOT NULL, "Type" varchar(50) NOT NULL CONSTRAINT "DF_96f08073d4209df8f157e66eec2" DEFAULT 'info', "IsRead" bit NOT NULL CONSTRAINT "DF_bb9558058ac6f04d07fe5d38880" DEFAULT 0, "CreatedAt" datetime NOT NULL CONSTRAINT "DF_185c018bf23ccd40d1435da8266" DEFAULT getdate(), CONSTRAINT "PK_3187c74ea5d53758c632e4dab87" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE INDEX "IX_Notifications_IsRead" ON "Notifications" ("IsRead") `);
        await queryRunner.query(`CREATE INDEX "IX_Notifications_UserId" ON "Notifications" ("UserId") `);
        await queryRunner.query(`CREATE TABLE "Teams" ("Id" int NOT NULL IDENTITY(1,1), "Name" nvarchar(255) NOT NULL, "Description" nvarchar(500), CONSTRAINT "PK_feed559811a78b46839f1380f54" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE TABLE "Users" ("Id" int NOT NULL IDENTITY(1,1), "Name" varchar(255) NOT NULL, "Email" varchar(255) NOT NULL, "PasswordHash" varchar(255) NOT NULL, "LastAccess" datetime, "Status" int NOT NULL CONSTRAINT "DF_64524b0ded0788e8647c397e9d0" DEFAULT 1, "TeamId" int, "BossId" int, "CreatedAt" datetime NOT NULL CONSTRAINT "DF_0aacbc61aa36d6a82383817a94d" DEFAULT getdate(), "UpdatedAt" datetime NOT NULL CONSTRAINT "DF_ed41b76bd60b64a976d388b6f33" DEFAULT getdate(), CONSTRAINT "UQ_884fdf47515c24dbbf6d89c2d84" UNIQUE ("Email"), CONSTRAINT "PK_329bb2946729a51bd2b19a5159f" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE INDEX "IX_Users_LastAccess" ON "Users" ("LastAccess") `);
        await queryRunner.query(`CREATE INDEX "IX_Users_Email" ON "Users" ("Email") `);
        await queryRunner.query(`CREATE TABLE "UserActionLogs" ("Id" int NOT NULL IDENTITY(1,1), "UserId" int, "Method" varchar(10) NOT NULL, "Url" varchar(500) NOT NULL, "Action" varchar(100) NOT NULL, "ResourceType" varchar(50), "ResourceId" varchar(50), "StatusCode" int NOT NULL, "IpAddress" varchar(45), "UserAgent" varchar(500), "RequestBody" text, "ResponseBody" text, "Metadata" text, "Duration" int, "ErrorMessage" text, "CreatedAt" datetime NOT NULL CONSTRAINT "DF_9d40255a05c72196c6b1a220501" DEFAULT getdate(), CONSTRAINT "PK_ac79367ce775ebc6f9ed19764ea" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE INDEX "IX_UserActionLogs_IpAddress" ON "UserActionLogs" ("IpAddress") `);
        await queryRunner.query(`CREATE INDEX "IX_UserActionLogs_CreatedAt" ON "UserActionLogs" ("CreatedAt") `);
        await queryRunner.query(`CREATE INDEX "IX_UserActionLogs_Action" ON "UserActionLogs" ("Action") `);
        await queryRunner.query(`CREATE INDEX "IX_UserActionLogs_UserId" ON "UserActionLogs" ("UserId") `);
        await queryRunner.query(`CREATE TABLE "Statuses" ("Id" int NOT NULL IDENTITY(1,1), "Name" nvarchar(50) NOT NULL, "Code" varchar(50) NOT NULL, "Order" int NOT NULL CONSTRAINT "DF_83f7520da451f7f5c446587ee34" DEFAULT 0, CONSTRAINT "UQ_dc1ed8167d50ba55639224d4db8" UNIQUE ("Code"), CONSTRAINT "PK_6eff60a532e72472b0bbc095e01" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE TABLE "SocioeconomicLevels" ("Id" int NOT NULL IDENTITY(1,1), "Name" nvarchar(100) NOT NULL, CONSTRAINT "PK_fa98c811a49ce73ff222fc01262" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE TABLE "RightsDurations" ("Id" int NOT NULL IDENTITY(1,1), "Name" nvarchar(100) NOT NULL, CONSTRAINT "PK_ae83dd7fb7f7f33a13b0e4df7dc" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE TABLE "CustomerData" ("Id" int NOT NULL IDENTITY(1,1), "ProductionRequestId" int NOT NULL, "RequestDate" datetime, "DeliveryDate" datetime, "ClientAgency" nvarchar(255), "RequesterName" nvarchar(255), "RequesterEmail" nvarchar(255), "RequesterPhone" nvarchar(50), "BusinessName" nvarchar(255), "NIT" nvarchar(50), "ServiceStrategy" bit NOT NULL CONSTRAINT "DF_f6ceafe5f76e31262303595cedc" DEFAULT 0, "ServiceTactical" bit NOT NULL CONSTRAINT "DF_5418c54267a3739948d846b83fe" DEFAULT 0, "ServiceProduction" bit NOT NULL CONSTRAINT "DF_5e76de8383e28acc7523abcf905" DEFAULT 0, "ServiceData" bit NOT NULL CONSTRAINT "DF_f34f6486560330980ebf6e90782" DEFAULT 0, CONSTRAINT "UQ_277577dbf3a786c3c891f6131c8" UNIQUE ("ProductionRequestId"), CONSTRAINT "PK_91d9ad157b2939fd9e454befc58" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "REL_277577dbf3a786c3c891f6131c" ON "CustomerData" ("ProductionRequestId") WHERE "ProductionRequestId" IS NOT NULL`);
        await queryRunner.query(`CREATE TABLE "Products" ("Id" int NOT NULL IDENTITY(1,1), "Name" nvarchar(255) NOT NULL, CONSTRAINT "PK_a70dbd7a49ef4bad9c0dc14cbd4" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE TABLE "CampaignProducts" ("Id" int NOT NULL IDENTITY(1,1), "CampaignDetailId" int NOT NULL, "ProductId" int NOT NULL, "Quantity" nvarchar(50) NOT NULL, CONSTRAINT "PK_81179fa6066ed20b2eb29e64031" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE TABLE "Objectives" ("Id" int NOT NULL IDENTITY(1,1), "Name" nvarchar(255) NOT NULL, CONSTRAINT "PK_748e7ed1b45b741ec1410ee3366" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE TABLE "CampaignDetails" ("Id" int NOT NULL IDENTITY(1,1), "ProductionRequestId" int NOT NULL, "Budget" nvarchar(100), "Brand" nvarchar(255), "ProductService" nvarchar(255), "ObjectiveId" int, CONSTRAINT "UQ_56a60c294a03459d2f91d5088f7" UNIQUE ("ProductionRequestId"), CONSTRAINT "PK_435385ce0261f6ebd39ef778eac" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "REL_56a60c294a03459d2f91d5088f" ON "CampaignDetails" ("ProductionRequestId") WHERE "ProductionRequestId" IS NOT NULL`);
        await queryRunner.query(`CREATE TABLE "Genders" ("Id" int NOT NULL IDENTITY(1,1), "Name" nvarchar(100) NOT NULL, CONSTRAINT "PK_2a5b2c4c4885e83739cd715b6ba" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE TABLE "AgeRanges" ("Id" int NOT NULL IDENTITY(1,1), "Name" nvarchar(100) NOT NULL, CONSTRAINT "PK_a6c39579ad4f12dbbd9a870bad0" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE TABLE "AudienceData" ("Id" int NOT NULL IDENTITY(1,1), "ProductionRequestId" int NOT NULL, "GenderId" int, "Geo" nvarchar(255), "AgeRangeId" int, "SocioEconomicLevelId" int, "Interests" nvarchar(MAX), "SpecificDetails" nvarchar(MAX), "CampaignContext" nvarchar(MAX), "CampaignConcept" nvarchar(MAX), "Assets" nvarchar(MAX), CONSTRAINT "UQ_f5ad8f8d54ccb8ebe83da6aa1e3" UNIQUE ("ProductionRequestId"), CONSTRAINT "PK_dfbc64ec4f5278a8c12dabc91fc" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "REL_f5ad8f8d54ccb8ebe83da6aa1e" ON "AudienceData" ("ProductionRequestId") WHERE "ProductionRequestId" IS NOT NULL`);
        await queryRunner.query(`CREATE TABLE "ProductionRequests" ("Id" int NOT NULL IDENTITY(1,1), "Name" nvarchar(255) NOT NULL, "RequestDate" datetime NOT NULL, "Department" nvarchar(255) NOT NULL, "ContactPerson" nvarchar(255) NOT NULL, "AssignedUserId" int, "StatusId" int, "DeliveryDate" datetime, "Observations" nvarchar(MAX), CONSTRAINT "PK_5a5c7ef9ed11ec0f29bfda39d7c" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE INDEX "IX_ProductionRequests_RequestDate" ON "ProductionRequests" ("RequestDate") `);
        await queryRunner.query(`CREATE TABLE "FormatTypes" ("Id" int NOT NULL IDENTITY(1,1), "Name" nvarchar(100) NOT NULL, CONSTRAINT "PK_9f4dd5e9439d85c5c5e26a41304" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE TABLE "ProductionInfo" ("Id" int NOT NULL IDENTITY(1,1), "ProductionRequestId" int NOT NULL, "FormatTypeId" int, "RightsDurationId" int, "CampaignEmissionDate" datetime, "CommunicationTone" nvarchar(255), "OwnAndExternalMedia" nvarchar(MAX), "TvFormats" nvarchar(MAX), "DigitalFormats" nvarchar(MAX), "ProductionDetails" nvarchar(MAX), "AdditionalComments" nvarchar(MAX), CONSTRAINT "UQ_928d14f982571a2c5d56aad3e84" UNIQUE ("ProductionRequestId"), CONSTRAINT "PK_76b41a7df557b2f809c48536b5e" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "REL_928d14f982571a2c5d56aad3e8" ON "ProductionInfo" ("ProductionRequestId") WHERE "ProductionRequestId" IS NOT NULL`);
        await queryRunner.query(`CREATE TABLE "ProductionRequestHistories" ("Id" int NOT NULL IDENTITY(1,1), "ProductionRequestId" int NOT NULL, "ChangeField" nvarchar(255) NOT NULL, "OldValue" nvarchar(MAX), "NewValue" nvarchar(MAX), "ChangedBy" int NOT NULL, "ChangeType" nvarchar(50) NOT NULL, "CreatedAt" datetime NOT NULL CONSTRAINT "DF_e299e8651d6eb5cc792fd92df24" DEFAULT getdate(), CONSTRAINT "PK_3a25b133bc91eae225f39ef8e51" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE TABLE "MenuItems" ("Id" int NOT NULL IDENTITY(1,1), "Label" nvarchar(100) NOT NULL, "Icon" nvarchar(50), "Route" nvarchar(255), "ParentId" int, "DisplayOrder" int NOT NULL CONSTRAINT "DF_eae95fc11e32afaefa9786eb6a6" DEFAULT 0, "IsActive" bit NOT NULL CONSTRAINT "DF_4ca7264fd68286a8c4317f89128" DEFAULT 1, "PermissionId" int, CONSTRAINT "PK_0879ed0ca99179839a40380ce89" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE INDEX "IX_MenuItems_DisplayOrder" ON "MenuItems" ("DisplayOrder", "IsActive") `);
        await queryRunner.query(`CREATE TABLE "Covers15Minutes" ("id" int NOT NULL IDENTITY(1,1), "uploaderLog" nvarchar(MAX) NOT NULL, "timestamp" datetime NOT NULL, "url" nvarchar(MAX) NOT NULL, CONSTRAINT "PK_802d14cb31e40b1ffbfe2bad463" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "PermissionsByUser" ADD CONSTRAINT "FK_9ebeea21a52ecc4731918ff2f22" FOREIGN KEY ("UserId") REFERENCES "Users"("Id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "PermissionsByUser" ADD CONSTRAINT "FK_a29ec070e7cd28d3d48bf22e2b3" FOREIGN KEY ("PermissionId") REFERENCES "Permissions"("Id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "LoadDocumentsOcByUser" ADD CONSTRAINT "FK_a5616e93e2db51b27010c67d9fd" FOREIGN KEY ("IdUser") REFERENCES "Users"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Notifications" ADD CONSTRAINT "FK_5b8b410cafd7b9c05ab77726482" FOREIGN KEY ("UserId") REFERENCES "Users"("Id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Users" ADD CONSTRAINT "FK_f0af88f040a4d545e243e0e1e4f" FOREIGN KEY ("TeamId") REFERENCES "Teams"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Users" ADD CONSTRAINT "FK_26611ec728b7ab0a778eeea40c9" FOREIGN KEY ("BossId") REFERENCES "Users"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "UserActionLogs" ADD CONSTRAINT "FK_7b6e5e8481f97ab31c2152ed8e9" FOREIGN KEY ("UserId") REFERENCES "Users"("Id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "CustomerData" ADD CONSTRAINT "FK_277577dbf3a786c3c891f6131c8" FOREIGN KEY ("ProductionRequestId") REFERENCES "ProductionRequests"("Id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "CampaignProducts" ADD CONSTRAINT "FK_c1de3f1cf1ddd072ce4454d92a3" FOREIGN KEY ("CampaignDetailId") REFERENCES "CampaignDetails"("Id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "CampaignProducts" ADD CONSTRAINT "FK_acd743097b48d8d41f87f6b2b2f" FOREIGN KEY ("ProductId") REFERENCES "Products"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "CampaignDetails" ADD CONSTRAINT "FK_56a60c294a03459d2f91d5088f7" FOREIGN KEY ("ProductionRequestId") REFERENCES "ProductionRequests"("Id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "CampaignDetails" ADD CONSTRAINT "FK_bbd6fd6657ad64886b0ccce29bb" FOREIGN KEY ("ObjectiveId") REFERENCES "Objectives"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "AudienceData" ADD CONSTRAINT "FK_f5ad8f8d54ccb8ebe83da6aa1e3" FOREIGN KEY ("ProductionRequestId") REFERENCES "ProductionRequests"("Id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "AudienceData" ADD CONSTRAINT "FK_ec174219c6e4266e158ef85a198" FOREIGN KEY ("GenderId") REFERENCES "Genders"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "AudienceData" ADD CONSTRAINT "FK_1654087cec3712722e4fff0ddea" FOREIGN KEY ("AgeRangeId") REFERENCES "AgeRanges"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "AudienceData" ADD CONSTRAINT "FK_ec32be2eb625ab708bfd3a95efc" FOREIGN KEY ("SocioEconomicLevelId") REFERENCES "SocioeconomicLevels"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ProductionRequests" ADD CONSTRAINT "FK_7229206609f1ad99612767c53bc" FOREIGN KEY ("AssignedUserId") REFERENCES "Users"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ProductionRequests" ADD CONSTRAINT "FK_12ab54b61ed75e584dcb8259e14" FOREIGN KEY ("StatusId") REFERENCES "Statuses"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ProductionInfo" ADD CONSTRAINT "FK_928d14f982571a2c5d56aad3e84" FOREIGN KEY ("ProductionRequestId") REFERENCES "ProductionRequests"("Id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ProductionInfo" ADD CONSTRAINT "FK_8239271cda546a38cd29883aa5b" FOREIGN KEY ("FormatTypeId") REFERENCES "FormatTypes"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ProductionInfo" ADD CONSTRAINT "FK_8edc3eaac5a57d81c1d2c02ce52" FOREIGN KEY ("RightsDurationId") REFERENCES "RightsDurations"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ProductionRequestHistories" ADD CONSTRAINT "FK_88d38071710ec9413ab3b2a28dc" FOREIGN KEY ("ProductionRequestId") REFERENCES "ProductionRequests"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ProductionRequestHistories" ADD CONSTRAINT "FK_b8907eb4e4bb0c5d2a4a421b266" FOREIGN KEY ("ChangedBy") REFERENCES "Users"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "MenuItems" ADD CONSTRAINT "FK_ee2d2372129c05cfe5d1bb55d0d" FOREIGN KEY ("ParentId") REFERENCES "MenuItems"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "MenuItems" ADD CONSTRAINT "FK_53f41f779ad0b4b507958a6c759" FOREIGN KEY ("PermissionId") REFERENCES "Permissions"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "MenuItems" DROP CONSTRAINT "FK_53f41f779ad0b4b507958a6c759"`);
        await queryRunner.query(`ALTER TABLE "MenuItems" DROP CONSTRAINT "FK_ee2d2372129c05cfe5d1bb55d0d"`);
        await queryRunner.query(`ALTER TABLE "ProductionRequestHistories" DROP CONSTRAINT "FK_b8907eb4e4bb0c5d2a4a421b266"`);
        await queryRunner.query(`ALTER TABLE "ProductionRequestHistories" DROP CONSTRAINT "FK_88d38071710ec9413ab3b2a28dc"`);
        await queryRunner.query(`ALTER TABLE "ProductionInfo" DROP CONSTRAINT "FK_8edc3eaac5a57d81c1d2c02ce52"`);
        await queryRunner.query(`ALTER TABLE "ProductionInfo" DROP CONSTRAINT "FK_8239271cda546a38cd29883aa5b"`);
        await queryRunner.query(`ALTER TABLE "ProductionInfo" DROP CONSTRAINT "FK_928d14f982571a2c5d56aad3e84"`);
        await queryRunner.query(`ALTER TABLE "ProductionRequests" DROP CONSTRAINT "FK_12ab54b61ed75e584dcb8259e14"`);
        await queryRunner.query(`ALTER TABLE "ProductionRequests" DROP CONSTRAINT "FK_7229206609f1ad99612767c53bc"`);
        await queryRunner.query(`ALTER TABLE "AudienceData" DROP CONSTRAINT "FK_ec32be2eb625ab708bfd3a95efc"`);
        await queryRunner.query(`ALTER TABLE "AudienceData" DROP CONSTRAINT "FK_1654087cec3712722e4fff0ddea"`);
        await queryRunner.query(`ALTER TABLE "AudienceData" DROP CONSTRAINT "FK_ec174219c6e4266e158ef85a198"`);
        await queryRunner.query(`ALTER TABLE "AudienceData" DROP CONSTRAINT "FK_f5ad8f8d54ccb8ebe83da6aa1e3"`);
        await queryRunner.query(`ALTER TABLE "CampaignDetails" DROP CONSTRAINT "FK_bbd6fd6657ad64886b0ccce29bb"`);
        await queryRunner.query(`ALTER TABLE "CampaignDetails" DROP CONSTRAINT "FK_56a60c294a03459d2f91d5088f7"`);
        await queryRunner.query(`ALTER TABLE "CampaignProducts" DROP CONSTRAINT "FK_acd743097b48d8d41f87f6b2b2f"`);
        await queryRunner.query(`ALTER TABLE "CampaignProducts" DROP CONSTRAINT "FK_c1de3f1cf1ddd072ce4454d92a3"`);
        await queryRunner.query(`ALTER TABLE "CustomerData" DROP CONSTRAINT "FK_277577dbf3a786c3c891f6131c8"`);
        await queryRunner.query(`ALTER TABLE "UserActionLogs" DROP CONSTRAINT "FK_7b6e5e8481f97ab31c2152ed8e9"`);
        await queryRunner.query(`ALTER TABLE "Users" DROP CONSTRAINT "FK_26611ec728b7ab0a778eeea40c9"`);
        await queryRunner.query(`ALTER TABLE "Users" DROP CONSTRAINT "FK_f0af88f040a4d545e243e0e1e4f"`);
        await queryRunner.query(`ALTER TABLE "Notifications" DROP CONSTRAINT "FK_5b8b410cafd7b9c05ab77726482"`);
        await queryRunner.query(`ALTER TABLE "LoadDocumentsOcByUser" DROP CONSTRAINT "FK_a5616e93e2db51b27010c67d9fd"`);
        await queryRunner.query(`ALTER TABLE "PermissionsByUser" DROP CONSTRAINT "FK_a29ec070e7cd28d3d48bf22e2b3"`);
        await queryRunner.query(`ALTER TABLE "PermissionsByUser" DROP CONSTRAINT "FK_9ebeea21a52ecc4731918ff2f22"`);
        await queryRunner.query(`DROP TABLE "Covers15Minutes"`);
        await queryRunner.query(`DROP INDEX "IX_MenuItems_DisplayOrder" ON "MenuItems"`);
        await queryRunner.query(`DROP TABLE "MenuItems"`);
        await queryRunner.query(`DROP TABLE "ProductionRequestHistories"`);
        await queryRunner.query(`DROP INDEX "REL_928d14f982571a2c5d56aad3e8" ON "ProductionInfo"`);
        await queryRunner.query(`DROP TABLE "ProductionInfo"`);
        await queryRunner.query(`DROP TABLE "FormatTypes"`);
        await queryRunner.query(`DROP INDEX "IX_ProductionRequests_RequestDate" ON "ProductionRequests"`);
        await queryRunner.query(`DROP TABLE "ProductionRequests"`);
        await queryRunner.query(`DROP INDEX "REL_f5ad8f8d54ccb8ebe83da6aa1e" ON "AudienceData"`);
        await queryRunner.query(`DROP TABLE "AudienceData"`);
        await queryRunner.query(`DROP TABLE "AgeRanges"`);
        await queryRunner.query(`DROP TABLE "Genders"`);
        await queryRunner.query(`DROP INDEX "REL_56a60c294a03459d2f91d5088f" ON "CampaignDetails"`);
        await queryRunner.query(`DROP TABLE "CampaignDetails"`);
        await queryRunner.query(`DROP TABLE "Objectives"`);
        await queryRunner.query(`DROP TABLE "CampaignProducts"`);
        await queryRunner.query(`DROP TABLE "Products"`);
        await queryRunner.query(`DROP INDEX "REL_277577dbf3a786c3c891f6131c" ON "CustomerData"`);
        await queryRunner.query(`DROP TABLE "CustomerData"`);
        await queryRunner.query(`DROP TABLE "RightsDurations"`);
        await queryRunner.query(`DROP TABLE "SocioeconomicLevels"`);
        await queryRunner.query(`DROP TABLE "Statuses"`);
        await queryRunner.query(`DROP INDEX "IX_UserActionLogs_UserId" ON "UserActionLogs"`);
        await queryRunner.query(`DROP INDEX "IX_UserActionLogs_Action" ON "UserActionLogs"`);
        await queryRunner.query(`DROP INDEX "IX_UserActionLogs_CreatedAt" ON "UserActionLogs"`);
        await queryRunner.query(`DROP INDEX "IX_UserActionLogs_IpAddress" ON "UserActionLogs"`);
        await queryRunner.query(`DROP TABLE "UserActionLogs"`);
        await queryRunner.query(`DROP INDEX "IX_Users_Email" ON "Users"`);
        await queryRunner.query(`DROP INDEX "IX_Users_LastAccess" ON "Users"`);
        await queryRunner.query(`DROP TABLE "Users"`);
        await queryRunner.query(`DROP TABLE "Teams"`);
        await queryRunner.query(`DROP INDEX "IX_Notifications_UserId" ON "Notifications"`);
        await queryRunner.query(`DROP INDEX "IX_Notifications_IsRead" ON "Notifications"`);
        await queryRunner.query(`DROP TABLE "Notifications"`);
        await queryRunner.query(`DROP TABLE "LoadDocumentsOcByUser"`);
        await queryRunner.query(`DROP INDEX "IX_PermissionsByUser_UserId" ON "PermissionsByUser"`);
        await queryRunner.query(`DROP TABLE "PermissionsByUser"`);
        await queryRunner.query(`DROP TABLE "Permissions"`);
    }

}
